name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: logi n to dockerhub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: build docker image
        run: |
          docker build . -t mbjobb/spring-docker-dockerhub
          
        
      - name: push docker image to dockerhub
        run: |
          docker push mbjobb/spring-docker-dockerhub
          
          
      - name: push Docker image to ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com 
          docker tag mbjobb/spring-docker-dockerhub 244530008913.dkr.ecr.eu-west-1.amazonaws.com/mabr/ecr-test
          docker push mbjobb/spring-docker-dockerhub 244530008913.dkr.ecr.eu-west-1.amazonaws.com/mabr/ecr-test
      